### ISSUE TITLE
Add support for PHP 7.3

### ISSUE THREAD

**Issue by brotkrueml** [Nimut/TYPO3-testing-framework#108]
Currently the requirements for PHP in composer.json is set to

    "php": ">= 5.5, < 7.3"

so it can't be used in PHP 7.3.

**Comment by IchHabRecht** [comment]
Hi @brotkrueml,

Your remark is correct. There is already a pull request for PHP 7.3 support but unfortunately we do have dependencies that do not support PHP 7.3 currently neither. We will work on that issue but I can't tell you any time frame for an upcoming release.
