### ISSUE TITLE
Add support for PHPUnit 8

### ISSUE THREAD

**Issue by davdenic** [Nimut/TYPO3-testing-framework#119]
Currently PHPUnit 6 || 7   are  supported, it would be good to also support the 8 release.
thanks :)

**Comment by IchHabRecht** [comment]
Hi @davdenic,

Thank you for your request. I had a look at the integration but version 8 of PHPUnit would require PHP 7.1 at minimum and support for PHPUnit 6/7 is not compatible anymore. Would you mind to share the advantages you see for that support?

**Comment by davdenic** [comment]
Hi, sorry for late reply, I basically want to rid off the annoying message "Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested."
This happens since phpunit-mock-objects was merged in phpunit 8.

About the minimun php version, is it for TYPO3 8.7 right? because version 9.5 requires php 7.2 if i'm not wrong. 
But if i'm not wrong it' just an OR, so people could still use version 6 or 7 if they prefer?

Thanks :)

**Comment by IchHabRecht** [comment]
Hi @davdenic,

Due to return type usage in PHPUnit version 8 it will not be possible to use version 6/7 and 8 in any project together. Once compatibility of the testing-framework to TYPO3 version 8.7 is dropped, we can raise the PHPUnit version as well. I will add a milestone to this ticket.

**Comment by vergissberlin** [comment]
This package currently gets in conflict with the current TYPO3 requirements. 
```
codeception/phpunit-wrapper        8.1.1              PHPUnit classes used ...
phpstan/phpstan-phpunit            0.12.7             PHPUnit extensions an...
phpunit/php-code-coverage          7.0.10             Library that provides...
phpunit/php-file-iterator          2.0.2              FilterIterator implem...
phpunit/php-text-template          1.2.1              Simple template engine.
phpunit/php-timer                  2.1.2              Utility class for timing
phpunit/php-token-stream           3.1.1              Wrapper around PHP's ...
phpunit/phpunit                    8.5.2              The PHP Unit Testing ...
sebastian/code-unit-reverse-lookup 1.0.1              Looks up which functi...
```

**Comment by IchHabRecht** [comment]
Hi @vergissberlin,

Would you mind to share some more information about your use case? I couldn't currently imagine any scenario where you have conflicts to any TYPO3 core dependencies. Thank you in advanced.
