### ISSUE TITLE
Linked fixtures are deleted before last test of a class

### ISSUE THREAD

**Issue by ndq1** [Nimut/TYPO3-testing-framework#125]
Hi,

I have (nimut) phpunit testing implemented in my project. Recently I noticed that after the first test ran the linked test/fixture folder (by $pathsToLinkInTestInstance) has been deleted. So all the tests afterwards are failing due to missing fixtures. 

After some research I found out that it is related to [this bugfix](https://github.com/Nimut/testing-framework/commit/9b958ba296d4184645b39cf2bcf4f964f51c8487?diff=split). I guess this modification is logical.

But then again is there a way to prevent a teardown of the linked files/folders when not all tests from that class has been executed?

Thanks for the help

**Comment by ndq1** [comment]
Hi @IchHabRecht,

Sorry to disturb you but just for understanding it correctly. The loop which removes the directory/link could be completely removed from the tearDown() function? Since the linked files/folders are used for the test. So no new "import" are necessary.

**Comment by IchHabRecht** [comment]
Hi @ndq1,

I'm not sure why the tearDown was added and need to check the code.

**Comment by ndq1** [comment]
Hi @IchHabRecht,

I just created a [pull request](https://github.com/Nimut/testing-framework/pull/127) so I can use it in my project. Also you can merge the change if it is ok for you.

Cheers

**Comment by IchHabRecht** [comment]
Hi @ndq1,

As you can see I already created a pull request against the current stable (released) 4.x branch that got merged already. I'm closing this issue now as it is resolved.
