### ISSUE TITLE
Add support for TYPO3 v11

### ISSUE THREAD

**Issue by rvock** [Nimut/TYPO3-testing-framework#143]
The `composer.json` specifies support for TYPO3 v11. But when trying to run test cases with TYPO3 v11, I get the following error:

```
 Uncaught TypeError: Argument 2 passed to TYPO3\CMS\Core\Core\Bootstrap::createPackageManager() must be an instance of TYPO3\CMS\Core\Package\Cache\PackageCacheInterface, instance of TYPO3\CMS\Core\Cache\Frontend\PhpFrontend given
```

[CoreBootstrap Line 247](https://github.com/TYPO3/typo3/blob/7a6e05a223c4a962b0f14e4e89e9b4a76b183ccb/typo3/sysext/core/Classes/Core/Bootstrap.php#L247) expects `PackageCacheInterface` instead of `FrontendInterface` since https://github.com/TYPO3/typo3/commit/6cfc1a10b946cf1e1729745aedcd6923adcac38c

There is a new helper method `Bootstrap::createPackageCache`, which converts a `FrontendInterface` into a `PackageCacheInterface` interface.

**Comment by tomasnorre** [comment]
I think this issue can be closed?

**Comment by rvock** [comment]
@tomasnorre Yes the issue can be closed. For my project, I've switched to [typo3/testing-framework](https://github.com/typo3/testing-framework/) which works with TYPO3 v11.

But I also checked just now and the current version of `nimut/testing-framework` works as well.
