### ISSUE TITLE
Document $testExtensionsToLoad (or provide useful error message)

### ISSUE THREAD

**Issue by maurii90** [Nimut/TYPO3-testing-framework#28]
For functional tests [`$testExtensionsToLoad`](https://github.com/Nimut/testing-framework/blob/master/src/TestingFramework/TestCase/FunctionalTestCase.php#L50-L70) needs provided if you need to access functionality from (other) extensions.

This is not obvious and should be nicely documented. Alternatively, the framework could provide an error message when test execution fail simply because an appropriate definition of the variable is missing (if this is possible).

Cc @comsolit, @robert197, @bittner

**Comment by IchHabRecht** [comment]
Hi mauri90,

Thank you for your issue. Did you had a look at the official wiki article about functional testing on https://wiki.typo3.org/Functional_testing#How_to_write_functional_test.3F

Would you mind to suggest a pull request how you would like to see this issue be solved?

Thank you very much.

**Comment by IchHabRecht** [comment]
Resolved with merge of #43
