### ISSUE TITLE
Few sentences in README about purposes of this lib

### ISSUE THREAD

**Issue by dkd-kaehm** [Nimut/TYPO3-testing-framework#32]
Hi,
could someone explain following things:

* parallels with typo3/testing-framework
* why nimut/testing-framework and not typo3/testing-framework or vice versa or using in parallel
* etc.

Thanks

**Comment by IchHabRecht** [comment]
Hi dkd-kaehm,

as written in the Readme.md

> The aim of the testing framework is to provide a good way to write and run unit and functional tests for multiple versions of the TYPO3 CMS. Currently TYPO3 CMS 6.2 up to master (8.6) are tested and supported. 

Does this help you to solve your problem?

**Comment by dkd-kaehm** [comment]
yes, partially. 
Why should somebody prefer nimut/testing-framework and not typo3/testing-framework?

**Comment by helhum** [comment]
> Why should somebody prefer nimut/testing-framework and not typo3/testing-framework?

With nimut/testing-framework you can test your extensions against TYPO3 6.2 and 7.6, with typo3/testing-framework you can't
