### ISSUE TITLE
Make it possible to test against TYPO3 CMS 9.x-dev

### ISSUE THREAD

**Issue by dkd-kaehm** [Nimut/TYPO3-testing-framework#37]
Is it possible to run tests against TYPO3 CMS 9.x-dev?

Are more changes needed as just increasing the maximal CMS version in composer.json?

**Comment by IchHabRecht** [comment]
Yes, we need to change DB api usage to Doctrine as well as implement the support for phpunit 6

**Comment by IchHabRecht** [comment]
Hi dkd-kaehm,

With the new version 2.0.0 you should be able to test against the current master of TYPO3 CMS. Please be aware the we cannot raise the allowed version number as there isn't any TYPO3 CMS 9 release yet. Please require TYPO3 CMS "dev-master as 8.7.0" to enable testing in your extension.

**Comment by dkd-kaehm** [comment]
@IchHabRecht thanks for your answer. 
I tried version 2.0 just now and it works as expected -> see [Solr Pull Request](https://github.com/TYPO3-Solr/ext-solr/pull/1641) and [Travis Job for CMS @dev-master](https://travis-ci.org/TYPO3-Solr/ext-solr/jobs/274081786).
This Job fails, which is OK for now. 

Which is best praxis for handling fixtures for removed database fields?
Is maybe something like that usable?

```
    <pages>
        ....
        <urltype library="typo3/cms" version="<8.7.999">1</urltype>
    </pages>
</dataset>
```
Include `urltype` field if CMS version smaller than "8.7.999"....

Or is something similar already possible without having multiple fixture files?

**Comment by IchHabRecht** [comment]
Hi dkd-kaehm,

Thank you for your feedback.

According to your problem with the removed database field: as I understand you have to support multiple versions of TYPO3 CMS. One that still supports the database field and one without that field. I would recommend to have different fixture files for each version and import the appropriate according to the current TYPO3 CMS version.
