### ISSUE TITLE
Link current project as extension into test system

### ISSUE THREAD

**Issue by mbrodala** [Nimut/TYPO3-testing-framework#50]
The property `$testExtensionsToLoad` of `FunctionalTestCase` can be used to link extensions installed as dependencies into test systems of functional tests.

However, when executing functional tests for an extension itself, there is no way to have it linked and activated here since it doesn't exist as extension in the current project's `<web-dir>/typo3conf/ext`.

Currently I work around this by manually adding a link to the current project like this:

```php
/**
 * @return void
 */
protected function setUp()
{
    $rootPath = dirname(__FILE__, 3);
    if (!is_link(ORIGINAL_ROOT . 'typo3conf/ext/my_extension')) {
        symlink($rootPath, ORIGINAL_ROOT . 'typo3conf/ext/my_extension');
    }
    parent::setUp();
}
```

(Assuming `__FILE__` exists in `Tests/Functional/FooTest.php`)

Afterwards `typo3conf/ext/my_extension` can be added to `$testExtensionsToLoad` and it will be linked and activated.

Any idea how this could be improved?

**Comment by mbrodala** [comment]
Another option are Composer packages which allow to [create arbitrary symlinks](https://packagist.org/packages/doppy/composer-symlink).

**Comment by IchHabRecht** [comment]
Hi @mbrodala,

What is wrong with the solution doing the link in the script part of the composer.json currently the default solution for TYPO3 extensions?

```
  "scripts": {
    "post-autoload-dump": [
      "mkdir -p .Build/typo3conf/ext/",
      "[ -L .Build/typo3conf/ext/my_extension ] || ln -snvf ../../../ .Build/typo3conf/ext/my_extension"
    ]
  },
```

**Comment by mbrodala** [comment]
That's what I [basically did](https://github.com/pagemachine/typo3-flat-urls/commit/8f1457b677a43984ba0101a1536189b13ee28bf6) now. However, maybe the testing framework could provide a solution for this which just works ™️ .

**Comment by IchHabRecht** [comment]
Hi @mbrodala,

I don't want to do anything else than the TYPO3/testing-framework does. So having the link either in the script section or in your deployment script seems to fit very well.

**Comment by mbrodala** [comment]
I guess this works for me right now altough I'd love a native/more flexible solution.
