### ISSUE TITLE
Missing $GLOBALS['LANG'] in TYPO3v7

### ISSUE THREAD

**Issue by mbrodala** [Nimut/TYPO3-testing-framework#51]
When running functional tests agains TYPO3v7 and e.g. using the `DataHandler` errors like this [can occur](https://travis-ci.org/pagemachine/typo3-flat-urls/jobs/302977771):

```
Error: Call to a member function substr() on null
/home/travis/build/[secure]/typo3-flat-urls/vendor/typo3/cms/typo3/sysext/core/Classes/DataHandling/DataHandler.php:1862
/home/travis/build/[secure]/typo3-flat-urls/vendor/typo3/cms/typo3/sysext/core/Classes/DataHandling/DataHandler.php:1744
/home/travis/build/[secure]/typo3-flat-urls/vendor/typo3/cms/typo3/sysext/core/Classes/DataHandling/DataHandler.php:1703
/home/travis/build/[secure]/typo3-flat-urls/vendor/typo3/cms/typo3/sysext/core/Classes/DataHandling/DataHandler.php:1542
/home/travis/build/[secure]/typo3-flat-urls/vendor/typo3/cms/typo3/sysext/core/Classes/DataHandling/DataHandler.php:1250
/home/travis/build/[secure]/typo3-flat-urls/Tests/Functional/PageTest.php:64
```

This happens because `$GLOBALS['LANG']` is not initialized anywhere. Adding the following to the tests [fixes the issue](https://travis-ci.org/pagemachine/typo3-flat-urls/builds/302980121):

```php
$GLOBALS['LANG'] = GeneralUtility::makeInstance(LanguageService::class);
$GLOBALS['LANG']->init(null);
```

This could be added to `FunctionalTestCase::setUpBackendUserFromFixture()` since [normally](https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_7-6/typo3/sysext/lang/Classes/LanguageService.php#L99-L100) `LanguageService::init()` should be called with `$GLOBALS['BE_USER']->uc['lang']`.

What do you think?

**Comment by IchHabRecht** [comment]
Hi @mbrodala,

Initializing the backend user does not mean the LanguageService needs to be initialized as well. The testing-framework doesn't know whether you need to use the LanguageService or not or you have to mock it for your tests. As the LanguageService is a dependency of your test case, you have to ensure it is available with your needs.

**Comment by IchHabRecht** [comment]
If you have a valid backend user, you can simply initialized the LanguageService with `\TYPO3\CMS\Core\Core\Bootstrap::getInstance()->initializeLanguageObject()`

**Comment by mbrodala** [comment]
That would require me to modify the test bootstrap AFAIS. But you're probably right. I've moved this to `setUp()` now which works for me.

**Comment by IchHabRecht** [comment]
Hi @mbrodala,

This is how it works even in the core tests :-)

**Comment by mbrodala** [comment]
Oh, you're [absolutely right](https://github.com/TYPO3/TYPO3.CMS/blob/080ef8cb3206c863e78bfd0b8345782c1de32a1f/typo3/sysext/workspaces/Tests/Functional/ActionHandler/ActionHandlerTest.php#L36). 👍
