### ISSUE TITLE
Unable to determine path to entry script.

### ISSUE THREAD

**Issue by simonschaufi** [Nimut/TYPO3-testing-framework#62]
in my extension i have the following typoscript snippet: https://github.com/helhum/ext_scaffold/blob/bb149b9e6a0ea3aaa3409879065bc4b05c5eafd5/composer.json

Since I require `typo3/cms-core` only, my .Build folder looks like this:

![grafik](https://user-images.githubusercontent.com/941794/34574296-4acd2af2-f177-11e7-9a37-65ec5c661e39.png)

but there is no `Web/typo3/index.php` file. This file only exists if I require the full core with `typo3/cms`

https://github.com/Nimut/testing-framework/blob/master/src/TestingFramework/Bootstrap/AbstractBootstrap.php#L138-L143

See also https://github.com/helhum/ext_scaffold/issues/10

**Comment by helhum** [comment]
you have three options: 
1. do `composer require --dev typo3/cms ^8.7` right before testing
1. add `typo3/cms` to your require-dev section
1. add `helhum/typo3-composer-setup` to your require-dev section. it will create the entry points for you in case typo3/cms is not required

By all means, **don't add** `typo3/cms` to your require section of your composer.json in your extension.

none of that is related to this project here, thus I'm closing this ticket

**Comment by simonschaufi** [comment]
Helmut as mentioned, I use the same json as in helhum/ext_scaffold. Whats the correct way of doing it? Please then also fix the composer.json in that scaffold extension.

**Comment by simonschaufi** [comment]
@helhum as mentioned, I use the same json as in helhum/ext_scaffold. Whats the correct way of doing it? Please then also fix the composer.json in that scaffold extension. I think option 3 is the best.

**Comment by helhum** [comment]
> Whats the correct way of doing it?

What worked (and was recommended) before, also works now (option 1 + 2).

What failed before (doing a `composer install` in an extension that only requires typo3/cms-core 8.7) also fails now. The only difference is, that you don't get a composer error message any more, as typo3/cms-core (in version 8.7.*) is now published on Packagist.

**Comment by simonschaufi** [comment]
ok, my test environment is running now but what about ext_scaffold?
