### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by oliverklee** [Nimut/TYPO3-testing-framework#63]
… so that I can use the testing framework with PHP 7.2 Thanks! :coffee:

**Comment by IchHabRecht** [comment]
Hi @oliverklee,

We released the version 3.0.0 of nimut/testing-framework today. For your information, I'd like to point out that our master version is always accessible by a branch name. I would recommend to use "3.x-dev" for your version constraint to always get the most recent version of the testing framework.

**Comment by oliverklee** [comment]
Thanks! :heart:
