### ISSUE TITLE
Update for TYPO3 9.4

### ISSUE THREAD

**Issue by mbrodala** [Nimut/TYPO3-testing-framework#94]
TYPO3 9.4 was released yesterday, this package should be updated accordingly.

**Comment by helhum** [comment]
Yes, we worked on it until 4:30 a.m. yesterday night/ today in the morning. There are some challenges to overcome…

**Comment by mbrodala** [comment]
OK, do you need some help? I just prepared a basic PR which was pointless then I guess. ;-)

**Comment by mbrodala** [comment]
(Please ignore my PR, I just think it is good to document that it's not that simple.)

**Comment by helhum** [comment]
Thanks. We now have a pretty good understanding why switching to new Bootstrap API failed for us. One thing is, that there is a TYPO3 bug in the doctrine connection subclass. However what we don't really understand, why this does not affect the typo3 testing framework.

**Comment by helhum** [comment]
That one actually worked https://github.com/Nimut/testing-framework/pull/93

But we did want to switch to new API instead.

**Comment by helhum** [comment]
Pending TYPO3 bugfix: https://review.typo3.org/#/c/58189/

**Comment by mbrodala** [comment]
Thanks a lot. Unfortunately I didn't have much time to test this yet especially since one place where I checked had all tests fail but I assume that's an error in my tests. At least the installation together with TYPO3 9.4 works now. :+1:
